name: lucky
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  retrofit: ^3.0.1+1
  dio: ^4.0.4
  money_formatter: ^0.0.3
  provider: ^5.0.0
  flutter_svg_provider: ^1.0.3
  font_awesome_flutter: ^9.2.0
  google_fonts: ^2.3.1
  date_count_down: ^1.0.2
  url_launcher: ^6.0.20
  shared_preferences: ^2.0.13
  clipboard: ^0.1.3

dev_dependencies:
  retrofit_generator: '>=4.0.0 <5.0.0'
  build_runner: '>2.1.0 <4.0.0' 
  json_serializable: '>4.4.0'
  flutter_launcher_icons: "^0.9.2"

  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/launcher_icon.png"

flutter:
  uses-material-design: true

  generate: true

  assets:
    - assets/images/
